server {
    listen 80 default_server;
    server_name networking-experiments.nju-slab.cn;
    server_tokens off;

    access_log /var/log/nginx/lab2_portal_access.log;
    error_log /var/log/nginx/lab2_portal_error.log;

    include /etc/nginx/conf.d/site-locations.inc;
}
